[build]
  publish = "public"
  command = "gatsby build"
  NETLIFY_USE_YARN = "true"
[build.environment]
  NODE_VERSION = "16.16.0"
[[plugins]]
  package = "@netlify/plugin-gatsby"    
[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
	  public,
	  max-age=2592000'''
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = '''
      https://donboulton.com,
      https://img.badgesize.io/, 
      https://www.unpkg.com/use-sound/dist/use-sound.esm.js.svg, 
      https://www.google-analytics.com/analytics.js,
      https://www.googletagmanager.com/gtag/js
      https://static.doubleclick.net, 
      https://cdn.viglink.com, 
      https://github.com, 
      https://bitbucket.status.atlassian.com, 
      https://links.services.disqus.com, 
      https://img.shields.io, 
      https://secure.gravatar.com, 
      https://identity.netlify.com, 
      https://media-library.cloudinary.com, 
      https://withspectrum.github.io, 
      https://cdn.rawgit.com 
      https://api.bitbucket.org, 
      https://widget.cloudinary.com, 
      https://www.youtube.com, 
      https://www.youtube.de, 
      https://cdn.lr-ingest.io, 
      https://d33wubrfki0l68.cloudfront.net, 
      https://www.googletagmanager.com,
      https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js,
      https://i.ytimg.com, 
      https://fonts.gstatic.com, 
      https://d33wubrfki0l68.cloudfront.net/0bd90e5ef8c6650f6ecc41a11a46d3f66e5a898e/dd6a2/static/roboto-latin-100-a45108d3b34af91f9113d827a183296d.woff
      https://d33wubrfki0l68.cloudfront.net/7d02b9455622a72bfc55a938a3e6bcccfcd57d0e/0abce/static/roboto-latin-100-c2aa4ab115bf9c6057cb59709d0e152b.woff2
      https://www.google-analytics.com, 
      https://storage.googleapis.com, 
      https://yt3.ggpht.com, 
      https://ocsp.digicert.com, 
      https://graph.facebook.com, 
      https://api.tumblr.com, 
      https://www.reddit.com, 
      https://googleads.g.doubleclick.net, 
      https://static.doubleclick.net, 
      https://api.applause-button.com, 
      https://apis.google.com, 
      https://r.lr-ingest.io, 
      https://connect.facebook.net, 
      https://res.cloudinary.com, 
      https://i.ytimg.com,
      https://api.github.com,
      https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js,
      https://stats.g.doubleclick.net/,
      https://www.google.com/recaptcha/api.js
    '''      
    Access-Control-Allow-Methods = '''
      POST, 
      GET,
      PUT,  
      DELETE,
      HEAD
    '''
    Access-Control-Allow-Credentials = "true"
    Vary = "Accept-Encoding"
    Permissions-Policy = '''
      accelerometer=(self),
      autoplay=(self),
      fullscreen=(self),
      geolocation=(self)
    '''
[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = '''
	  public,
	  max-age=31536000'''